server:
  port: 8081
spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:quickbite_auth}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
  rabbitmq:
    enabled: ${QUICKBITE_RABBITMQ_ENABLED:false}
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
jwt:
  secret: ${JWT_SECRET:quickbite-auth-default-secret-key-change-me-1234567890}
  expiration-ms: ${JWT_EXPIRATION_MS:86400000}
quickbite:
  google:
    client-id: ${GOOGLE_CLIENT_ID:657167715760-nl47ceicarqnu2q296mpl2fmm3oubh5t.apps.googleusercontent.com}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
